export const CONSEJOS_FITNESS = [
  // --- HIPERTROFIA Y CIENCIA DEL ENTRENAMIENTO ---
  { titulo: "🔥 Hipertrofia Real", texto: "La clave es acercarte al fallo muscular (RIR 1-2) sin importar si haces 8 o 15 repeticiones." },
  { titulo: "⚖️ Volumen de Entrenamiento", texto: "Entre 10 y 20 series efectivas por grupo muscular a la semana es el punto dulce para la mayoría." },
  { titulo: "🐢 Controla la Excéntrica", texto: "Bajar el peso de forma controlada produce mayor hipertrofia que simplemente dejarlo caer." },
  { titulo: "🔄 Rango de Recorrido (ROM)", texto: "Un rango completo con menos peso construye más músculo que medio recorrido con mucho peso." },
  { titulo: "🧠 Conexión Mente-Músculo", texto: "Concéntrate en sentir el músculo que trabajas para reclutar más fibras musculares." },
  { titulo: "🚀 Explosividad Concéntrica", texto: "Levanta el peso de la forma más rápida y explosiva posible para reclutar fibras de contracción rápida." },
  { titulo: "📏 Estiramiento bajo carga", texto: "Los ejercicios que enfatizan el estiramiento del músculo (como el peso muerto rumano) son potentes para la hipertrofia." },
  { titulo: "🧪 Tensión Mecánica", texto: "Es el factor más importante para crecer. Levanta pesos desafiantes con una técnica impecable." },
  { titulo: "🦠 Estrés Metabólico", texto: "Se logra con repeticiones altas y descansos cortos. Es el famoso 'bombeo' que ayuda al crecimiento secundario." },
  { titulo: "💪 Daño Muscular", texto: "No es necesario estar extremadamente dolorido para crecer. Demasiado daño puede retrasar tu recuperación." },
  { titulo: "🏗️ Selección de Ejercicios", texto: "Prioriza ejercicios multiarticulares (básicos) al principio de la sesión cuando tienes más energía." },
  { titulo: "🔝 Series de Aproximación", texto: "Haz series ligeras antes de tus series efectivas para preparar el sistema nervioso y las articulaciones." },
  { titulo: "📉 Series Descendentes (Drop Sets)", texto: "Al terminar una serie, baja el peso un 30% y sigue hasta el fallo para añadir fatiga metabólica." },
  { titulo: "⏸️ Pausa-Descanso (Rest-Pause)", texto: "Llega al fallo, descansa 15 segundos y haz unas pocas repeticiones más con el mismo peso." },
  { titulo: "🧱 Isométricos funcionales", texto: "Hacer una pausa de 1 segundo en la parte más difícil del ejercicio mejora el control y la fuerza." },

  // --- SOBRECARGA PROGRESIVA ---
  { titulo: "📈 Sobrecarga Progresiva", texto: "Subir kilos no es la única forma. Hacer una repetición más o mejorar la técnica también cuenta." },
  { titulo: "📝 Registra Todo", texto: "Lo que no se mide, no se puede mejorar. Apunta siempre tus pesos y repeticiones." },
  { titulo: "⏱️ Tiempos de Descanso", texto: "En ejercicios pesados, descansa 2-3 minutos. Tu sistema nervioso necesita recuperarse para rendir igual." },
  { titulo: "🗓️ Semanas de Descarga", texto: "Cada 6-8 semanas de entreno intenso, reduce el volumen a la mitad para disipar la fatiga acumulada." },
  { titulo: "🔄 Frecuencia de Entrenamiento", texto: "Entrenar cada músculo 2 veces por semana (Frecuencia 2) es superior a hacerlo solo una vez." },
  { titulo: "🎯 Micro-progresión", texto: "No subas 5kg de golpe. Usar discos pequeños de 0.5kg o 1kg permite progresar de forma constante sin estancarse." },
  { titulo: "⏳ Densidad de entrenamiento", texto: "Hacer el mismo trabajo en menos tiempo es una forma efectiva de progresar." },

  // --- NUTRICIÓN Y SUPLEMENTACIÓN ---
  { titulo: "🍗 Proteína Diaria", texto: "Apunta a entre 1.6g y 2.2g de proteína por kilo de peso corporal para asegurar la recuperación." },
  { titulo: "🥯 Carbohidratos = Gasolina", texto: "Son el combustible principal del entrenamiento de fuerza. No les tengas miedo en etapas de ganancia." },
  { titulo: "🥑 Grasas Saludables", texto: "Esenciales para mantener tus niveles de testosterona y salud hormonal en niveles óptimos." },
  { titulo: "🥪 Nutrición Peri-entreno", texto: "Consumir carbohidratos y proteína 1-2 horas antes de entrenar te dará energía para rendir." },
  { titulo: "💊 Creatina Monohidrato", texto: "5 gramos al día, todos los días. Mejora la fuerza, la potencia y la hidratación celular." },
  { titulo: "☕ Cafeína Pre-entreno", texto: "Toma 3-6mg por kilo de peso 45 minutos antes. Es de los pocos suplementos con evidencia real." },
  { titulo: "💧 Hidratación y Fuerza", texto: "Una deshidratación del 2% puede reducir tu fuerza máxima. Bebe agua durante toda la sesión." },
  { titulo: "🥤 Ventana Anabólica", texto: "No es necesario tomar el batido nada más soltar la pesa. Lo que importa es el total de proteína del día." },
  { titulo: "🥝 Vitaminas y Minerales", texto: "El magnesio y el zinc son claves para la contracción muscular y el descanso profundo." },
  { titulo: "🥛 Proteína de Suero (Whey)", texto: "Es solo comida en polvo. Úsala por comodidad si no llegas a tus requerimientos con comida sólida." },
  { titulo: "🧂 El Sodio es importante", texto: "Un poco de sal en tu comida pre-entreno puede mejorar el flujo sanguíneo y el 'pump'." },
  { titulo: "🥚 Valor biológico", texto: "El huevo tiene una de las proteínas de mejor calidad. No tires las yemas, tienen vitaminas clave." },
  { titulo: "🥦 Fibra y Digestión", texto: "Una buena salud intestinal mejora la absorción de nutrientes. No olvides los vegetales." },

  // --- DEFINICIÓN Y PÉRDIDA DE GRASA ---
  { titulo: "📉 Déficit Calórico", texto: "Para definir, debes gastar más de lo que consumes. Es la ley de la termodinámica." },
  { titulo: "🏋️‍♂️ Entrena Pesado en Definición", texto: "Dile a tu cuerpo que debe mantener el músculo porque lo sigue necesitando para mover cargas." },
  { titulo: "🚶 NEAT (Actividad no deportiva)", texto: "Caminar más es la forma más fácil de quemar calorías sin añadir fatiga excesiva." },
  { titulo: "🥗 Saciedad", texto: "Prioriza alimentos voluminosos y bajos en calorías (verduras, frutas) para no pasar hambre en dieta." },
  { titulo: "🍎 Comida Trampa (Cheat Meal)", texto: "Una comida no arruina tu dieta, al igual que una ensalada no te pone en forma. Consistencia es la clave." },
  { titulo: "🥤 Calorías líquidas", texto: "Evita zumos y refrescos con azúcar. Son calorías que no te sacian y se acumulan rápido." },
  { titulo: "🥩 Efecto térmico", texto: "La proteína gasta más energía en ser digerida que las grasas o carbos. Ayuda a quemar más calorías." },
  { titulo: "🥨 Refeeds (Recargas)", texto: "Subir los carbohidratos un día a la semana en definición ayuda a recuperar glucógeno y salud mental." },

  // --- FUERZA Y BIOMECÁNICA ---
  { titulo: "😤 Maniobra de Valsalva", texto: "Coge aire en el abdomen y aprieta antes de levantar. Protege tu columna en pesos pesados." },
  { titulo: "👟 Calzado de Suela Plana", texto: "Para Sentadilla y Peso Muerto, usa suela plana o descalzo para mayor estabilidad y fuerza." },
  { titulo: "📏 El 'Path' de la barra", texto: "En press banca o sentadilla, intenta que la barra viaje en línea recta vertical para ser más eficiente." },
  { titulo: "👐 Anchura del agarre", texto: "En press banca, un agarre muy ancho usa más pecho; uno más cerrado usa más tríceps." },
  { titulo: "🦵 Leg Drive en Press Banca", texto: "Empuja el suelo con los pies para estabilizar tu torso y levantar más peso con seguridad." },
  { titulo: "🧱 Retracción Escapular", texto: "Junta las escápulas al hacer presses para proteger tus hombros y crear una base sólida." },
  { titulo: "🗝️ El 'Lockout'", texto: "Finaliza el movimiento apretando el músculo (glúteos en peso muerto, tríceps en press) para máximo estímulo." },
  { titulo: "🏗️ Momento de fuerza", texto: "Cuanto más lejos esté el peso de tu articulación, más difícil será el ejercicio." },

  // --- RECUPERACIÓN Y SALUD ---
  { titulo: "💤 Sueño Profundo", texto: "El músculo crece mientras duermes. La falta de sueño eleva el cortisol y destruye músculo." },
  { titulo: "🤕 Manejo del Dolor", texto: "Si un ejercicio te duele (dolor punzante), busca una variante. No entrenes con lesiones." },
  { titulo: "🧘 Movilidad vs Flexibilidad", texto: "Tener movilidad es tener control en el rango de movimiento. Calienta con movilidad dinámica." },
  { titulo: "🧖 Baños de contraste", texto: "Alternar agua fría y caliente puede ayudar a la circulación y reducir la sensación de fatiga." },
  { titulo: "🎾 Masaje con rodillo (Foam Rolling)", texto: "Ayuda a relajar la fascia muscular y puede mejorar el rango de movimiento antes de entrenar." },
  { titulo: "🧘 Estrés Mental", texto: "El estrés del trabajo o estudios también gasta energía de recuperación. Ajusta tu entreno si estás agotado." },
  { titulo: "🚶 Recuperación Activa", texto: "Caminar o hacer cardio ligero los días de descanso mejora el flujo sanguíneo y la recuperación." },

  // --- PSICOLOGÍA Y DISCIPLINA ---
  { titulo: "🤝 Consistencia > Perfección", texto: "Es mejor entrenar 3 días siempre que 5 días solo una semana. La clave es el largo plazo." },
  { titulo: "🎯 Objetivos SMART", texto: "Ponte metas Específicas, Medibles, Alcanzables, Relevantes y con Tiempo definido." },
  { titulo: "📉 No te compares", texto: "Tu única referencia debe ser tu 'yo' de la semana pasada. Cada cuerpo progresa a ritmos distintos." },
  { titulo: "🧠 Mentalidad de Proceso", texto: "Disfruta del entrenamiento diario. El cambio físico es una consecuencia, no el único fin." },
  { titulo: "😤 Disciplina vs Motivación", texto: "La motivación te hace empezar, pero la disciplina te hace seguir cuando no tienes ganas." },
  { titulo: "🎭 El entorno importa", texto: "Rodéate de gente que tenga tus mismos objetivos. Es más fácil entrenar si tus amigos también lo hacen." },
  { titulo: "🧘 Visualización", texto: "Visualizar el levantamiento perfecto antes de hacerlo prepara a tu cerebro para ejecutarlo mejor." },

  // --- VARIANTES Y TÉCNICAS ADICIONALES ---
  { titulo: "⛓️ Cadenas y Bandas", texto: "Añaden resistencia variable: el ejercicio se vuelve más difícil donde tú eres más fuerte." },
  { titulo: "🛑 Repeticiones Pausadas", texto: "Elimina el rebote y el impulso. Te hace mucho más fuerte en la parte más débil del ejercicio." },
  { titulo: "🎭 Entrenamiento Unilateral", texto: "Hacer ejercicios a una pierna o brazo corrige descompensaciones y mejora la estabilidad central." },
  { titulo: "🌀 Concéntricas lentas", texto: "A veces, subir el peso despacio ayuda a corregir fallos técnicos y mejorar el control muscular." },
  { titulo: "🏗️ Pre-fatiga", texto: "Hacer un ejercicio de aislamiento antes que uno compuesto para 'sentir' mejor el músculo principal." },
  { titulo: "🦾 Agarre de gancho (Hook grip)", texto: "Técnica de halterofilia para que la barra no se resbale en pesos muertos muy pesados." },
  { titulo: "🦵 Sentadilla Búlgara", texto: "El ejercicio de pierna más odiado y a la vez uno de los más efectivos para glúteo y cuádriceps." },
  { titulo: "🤛 Press Palof", texto: "Excelente para trabajar la anti-rotación del core y proteger tu espalda." },
  { titulo: "🧗 Dominadas vs Jalones", texto: "Las dominadas requieren más control corporal; los jalones permiten aislar mejor el dorsal." },
  { titulo: "🚣 Remo con apoyo", texto: "Apoyar el pecho en un banco al hacer remo elimina el balanceo y enfoca todo el trabajo en la espalda." },
  { titulo: "🏹 Aperturas para pecho", texto: "Usa cables en lugar de mancuernas para mantener la tensión durante todo el recorrido." },
  { titulo: "🎢 Curva de fuerza", texto: "Entiende que cada ejercicio es más difícil en un punto distinto. Varía tus ejercicios para cubrirlos todos." },
  { titulo: "🧱 El 'Bracing'", texto: "No es solo apretar el abdomen, es crear presión intra-abdominal para estabilizar toda la columna." },
  { titulo: "🦶 Posición de los pies", texto: "En prensa de piernas, pies más altos usan más glúteo; pies más bajos usan más cuádriceps." },
  { titulo: "📐 Ángulo de abducción", texto: "Al hacer laterales de hombro, inclina el torso un poco hacia adelante para alinear mejor la fibra muscular." },
  { titulo: "🌑 Entrenamiento en ayunas", texto: "No quema más grasa por sí solo, pero a algunas personas les da más foco mental. Cuestión de preferencia." },
  { titulo: "🌞 Vitamina D", texto: "Clave para la fuerza y la salud ósea. Toma el sol o suplementa si vives en zonas con poco sol." },
  { titulo: "🥛 Caseína", texto: "Proteína de absorción lenta, ideal para antes de dormir para mantener el flujo de aminoácidos." },
  { titulo: "💊 Beta-Alanina", texto: "Ayuda a retrasar la fatiga en series de altas repeticiones (el famoso picor es normal)." },
  { titulo: "📊 Volumen de mantenimiento", texto: "La cantidad mínima de series para no perder músculo es mucho menor de la que crees. Úsalo en vacaciones." },
  { titulo: "🔥 NEAT y Salud", texto: "Moverse a diario mejora la sensibilidad a la insulina, ayudándote a gestionar mejor los carbohidratos." },
  { titulo: "🧠 Fatiga Central", texto: "Si tus pesos bajan de golpe en todos los ejercicios, tu cerebro necesita un descanso, no tus músculos." },
  { titulo: "💪 Bíceps y supinación", texto: "Para máximo pico de bíceps, gira la muñeca hacia afuera (meñique hacia arriba) al subir la mancuerna." },
  { titulo: "🦴 Salud Articular", texto: "No ignores los chasquidos con dolor. El cartílago no se regenera fácil; cuida tus articulaciones." },
  { titulo: "🏋️‍♂️ Intensidad vs Esfuerzo", texto: "Intensidad es % de tu peso máximo. Esfuerzo es cuánto te acercas al fallo. Ambos deben estar equilibrados." },
  { titulo: "🧼 Higiene del sueño", texto: "Habitación oscura, fría y sin pantallas 30 mins antes de dormir para segregar melatonina natural." },
  { titulo: "🥗 Comida real", texto: "El 80% de tu dieta debe venir de alimentos de un solo ingrediente. El 20% puede ser más flexible." },
  { titulo: "🥤 Batidos de protes caseros", texto: "Añade avena, crema de cacahuete y fruta a tu batido para un gainer saludable y potente." },
  { titulo: "🌡️ Temperatura corporal", texto: "Entrenar con un buen calentamiento sube la temperatura muscular, haciendo los tejidos más elásticos y fuertes." },
  { titulo: "📉 Cortisol y Grasa abdominal", texto: "El estrés crónico dificulta la pérdida de grasa. El gimnasio es estrés; asegúrate de compensarlo con relax." },
  { titulo: "⏳ El tiempo bajo tensión (TUT)", texto: "No es tan importante como la carga total, pero series de 30-45 segundos son ideales para hipertrofia." },
  { titulo: "🏅 Mentalidad de Atleta", texto: "No entrenes para 'quemar lo que has comido'. Entrena para ser más fuerte, rápido y funcional." }
];